# Generated by Django 2.0.4 on 2018-04-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('administrator', 'administrator')], default='user', max_length=20),
        ),
    ]
